# Generated by Django 4.2.1 on 2023-06-09 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_phones_number'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Phones',
            new_name='Phone',
        ),
    ]
