# Generated by Django 4.2.1 on 2023-06-04 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customer'),
        ),
        migrations.AddField(
            model_name='sale',
            name='description',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sales.plandescription'),
        ),
        migrations.AddField(
            model_name='sale',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.seller'),
        ),
        migrations.AddField(
            model_name='plan',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='users.customer'),
        ),
        migrations.AddField(
            model_name='plan',
            name='description',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sales.plandescription'),
        ),
        migrations.AddField(
            model_name='plan',
            name='sale',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sales.sale'),
        ),
    ]
