# Generated by Django 4.2.1 on 2023-06-04 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plan',
            old_name='description',
            new_name='plan_desc',
        ),
        migrations.RenameField(
            model_name='sale',
            old_name='description',
            new_name='plan_desc',
        ),
    ]
