# Generated by Django 4.2.1 on 2023-06-04 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_rename_description_plan_plan_desc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='plan_desc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.plandescription'),
        ),
    ]
