# Generated by Django 4.2.1 on 2023-06-04 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_alter_sale_plan_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='plan_desc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.plandescription'),
        ),
    ]
